[package]
name = "rust-parquet"
version = "0.1.0"
authors = ["Brent Gardner <bgardner@squarelabs.net>"]

[dependencies]
#arrow = "0.11.0"
arrow = { path = "../arrow/rust/arrow" }
parquet = { path = "../arrow/rust/parquet" }
